### ISSUE TITLE
etc directory landing in a non-standard directory

### ISSUE THREAD

**Issue by Narrat** [sebastinas/yafc#50]
Hi

Compiling and installing it yields the following result with the /etc directory

>./configure --prefix=/usr
make
make DESTDIR=pkg install

(Simplified build steps that are done to generate a package on Arch Linux)

>pkg/yafc
└── usr
    ├── bin
    │   └── yafc
    ├── etc
    │   └── bash_completion.d
    │       └── yafc
    └── share
        ├── info
        │   └── yafc.info.gz
        ├── locale
        │   ├── de
        │   │   └── LC_MESSAGES
        │   │       └── yafc.mo
        │   └── sv
        │       └── LC_MESSAGES
        │           └── yafc.mo
        └── man
            └── man1
                └── yafc.1.gz

And /usr/etc is not a standard directory. Normally that stuff should land directly into /etc

Edit: Visual effect is somewhat misleading. https://paste.archlinux.de/1XUj/

**Comment by sebastinas** [comment]
This is normal autotools behavior. If you want to have it in /etc, pass `--sysconfdir=/etc`.

**Comment by Narrat** [comment]
ugh, embarrassing. Forgot that this options exists

Thanks
