### ISSUE TITLE
Downloads from web are broken

### ISSUE THREAD

**Issue by cpages** [sebastinas/yafc#56]
Any file that you try to grab from here: http://www.yafc-ftp.com/download results in this error:
```
Forbidden

You don't have permission to access /upload/yafc-1.3.6.tar.xz on this server
```
I don't know why the download links point to upload, guess that's the problem.

**Comment by sebastinas** [comment]
Should be fixed by https://github.com/TheJosh/yafc-website/commit/2050944d6dbb3decafe42cbd3420111a7c6e783f until @TheJosh has time to look at yafc-ftp.com.

**Comment by TheJosh** [comment]
Hi,

Website was recently moved to a new host. I'll investigate the issue.

Cheers
Josh

**Comment by TheJosh** [comment]
This issue has been fixed.
